# dataset.xlsx

In [2]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_excel("dataset.xlsx")

In [39]:
df = data.iloc[:, :47]

In [40]:
to_drop = ["Serum Glucose", "Mycoplasma pneumoniae"]
df = df.drop(to_drop, axis = 1)

In [41]:
df.iloc[1]

Patient ID                                               126e9dd13932f68
Patient age quantile                                                  17
SARS-Cov-2 exam result                                          negative
Patient addmited to regular ward (1=yes, 0=no)                         0
Patient addmited to semi-intensive unit (1=yes, 0=no)                  0
Patient addmited to intensive care unit (1=yes, 0=no)                  0
Hematocrit                                                      0.236515
Hemoglobin                                                    -0.0223403
Platelets                                                      -0.517413
Mean platelet volume                                           0.0106766
Red blood Cells                                                 0.102004
Lymphocytes                                                     0.318366
Mean corpuscular hemoglobin concentrationÂ (MCHC)                -0.95079
Leukocytes                                                    -0.0946103
Basophils                                                      -0.223767
Mean corpuscular hemoglobin (MCH)                              -0.292269
Eosinophils                                                      1.48216
Mean corpuscular volume (MCV)                                   0.166192
Monocytes                                                       0.357547
Red blood cell distribution width (RDW)                        -0.625073
Respiratory Syncytial Virus                                 not_detected
Influenza A                                                 not_detected
Influenza B                                                 not_detected
Parainfluenza 1                                             not_detected
CoronavirusNL63                                             not_detected
Rhinovirus/Enterovirus                                          detected
Coronavirus HKU1                                            not_detected
Parainfluenza 3                                             not_detected
Chlamydophila pneumoniae                                    not_detected
Adenovirus                                                  not_detected
Parainfluenza 4                                             not_detected
Coronavirus229E                                             not_detected
CoronavirusOC43                                             not_detected
Inf A H1N1 2009                                             not_detected
Bordetella pertussis                                        not_detected
Metapneumovirus                                             not_detected
Parainfluenza 2                                             not_detected
Neutrophils                                                    -0.619086
Urea                                                             1.19806
Proteina C reativa mg/dL                                       -0.147895
Creatinine                                                       2.08993
Potassium                                                      -0.305787
Sodium                                                          0.862512
Influenza B, rapid test                                         negative
Influenza A, rapid test                                         negative
Name: 1, dtype: object

In [42]:
df.dropna()

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Metapneumovirus,Parainfluenza 2,Neutrophils,Urea,Proteina C reativa mg/dL,Creatinine,Potassium,Sodium,"Influenza B, rapid test","Influenza A, rapid test"
1,126e9dd13932f68,17,negative,0,0,0,0.236515,-0.022340,-0.517413,0.010677,...,not_detected,not_detected,-0.619086,1.198059,-0.147895,2.089928,-0.305787,0.862512,negative,negative
30,ebdd7c67fcb21b4,9,negative,1,0,0,-0.679027,-0.711556,0.952319,-0.886869,...,not_detected,not_detected,0.782232,-0.439476,0.545572,1.021638,0.435697,-1.653147,negative,negative
87,26000ea3dba0de1,17,negative,0,0,0,0.442512,0.228284,-0.680717,0.459449,...,not_detected,not_detected,1.478794,-0.365042,-0.404219,0.573645,-1.047272,-0.215628,negative,negative
133,33fd6f1c08760a1,17,negative,0,0,0,1.037616,0.854844,-0.354109,-0.662483,...,not_detected,not_detected,0.634725,0.751459,-0.511518,0.366879,0.682859,-0.575008,negative,negative
145,1205a978ff0ef00,12,negative,0,0,0,-0.404364,-0.523588,-0.592784,-0.550290,...,not_detected,not_detected,-0.430605,-0.960510,-0.203531,-0.287879,-1.541595,1.581271,negative,negative
193,c7493375e3a576c,3,negative,0,0,0,-1.365685,-1.338116,-1.534920,2.030154,...,not_detected,not_detected,0.806817,-1.332677,-0.396271,-0.632489,-0.552949,-0.215628,positive,negative
196,26bc5c882b8bebc,18,negative,0,0,0,1.106281,1.168124,-0.781211,0.122869,...,not_detected,not_detected,-1.192725,-1.183810,-0.487674,-0.873716,0.682859,0.503132,negative,negative
205,671655cb4b17c2e,3,negative,0,0,0,-0.793470,-0.899524,-1.183189,2.591120,...,not_detected,not_detected,1.962290,-0.960510,0.032923,-0.598028,-2.283079,-2.012527,negative,negative
226,0f77fabc0fe7a6c,13,negative,0,0,0,1.724273,1.606716,-1.522358,3.713052,...,not_detected,not_detected,0.503607,-0.439476,-0.497609,0.022270,-0.058626,-0.215628,negative,negative
671,0f2c3bd3954f19e,7,negative,0,1,0,-0.289922,-0.335620,0.223734,-0.213711,...,not_detected,not_detected,0.339711,-0.811643,-0.461843,-0.632489,-0.800110,0.862512,negative,negative
732,31bad60781945d3,6,negative,0,0,0,0.167850,0.040316,0.638273,0.459449,...,not_detected,not_detected,1.257534,-0.067309,-0.167765,-0.356801,-0.058626,0.143752,negative,negative
915,72eb26d2d535794,16,negative,0,0,0,0.076295,0.541564,-1.170627,0.796029,...,not_detected,not_detected,1.577132,-0.588343,0.952909,0.297958,0.682859,-1.293767,negative,negative
1027,e64b89d80b931a7,11,negative,0,0,0,0.328069,0.102972,-0.969638,0.122869,...,not_detected,not_detected,1.634496,-0.141742,0.402507,0.470262,-0.552949,0.143752,negative,negative
1039,b64bc1acd95fd62,19,negative,0,1,0,0.556955,0.478908,2.183376,-0.213711,...,not_detected,not_detected,2.019654,0.602592,5.499193,-0.666950,-0.552949,-1.293767,negative,negative
1108,9d7c293a6773d6a,14,positive,0,0,0,-0.312811,-0.648900,-0.027502,-0.101517,...,not_detected,not_detected,-0.315877,0.304858,-0.479726,-0.046652,0.682859,1.940651,negative,negative
1162,2a5db9bbb45109f,14,positive,0,0,0,-0.518807,-0.272964,-0.215930,0.459449,...,not_detected,not_detected,-0.127395,-0.588343,-0.340635,0.435801,-0.800110,-0.575008,negative,negative
1899,f34b99f344d9dc2,10,negative,0,0,0,0.991838,0.666876,-0.454604,-0.213711,...,not_detected,not_detected,1.314897,-0.067309,-0.459856,0.470262,-0.552949,1.221892,negative,negative
2045,d4ca212ea1641ad,9,negative,0,0,0,-0.633250,-0.648900,0.198610,0.347255,...,not_detected,not_detected,0.569166,-0.216176,-0.521453,0.091192,-0.800110,0.143752,negative,negative
2410,f4ec17c32d5f959,15,negative,0,0,0,-0.518807,-1.150148,1.002566,-0.774677,...,not_detected,not_detected,-0.422410,0.900325,-0.267116,-0.081113,0.188535,-0.575008,negative,negative
2708,1de5e88e6560cc7,8,negative,0,0,0,-0.656139,-0.460932,0.349352,0.459449,...,not_detected,not_detected,-0.438800,-0.588343,-0.439986,-0.115574,-0.058626,0.143752,negative,negative
3001,8331bc73200633e,13,negative,0,1,0,-1.640348,-2.089987,1.178431,-0.999063,...,not_detected,not_detected,2.126187,-0.439476,-0.223401,-0.908177,1.424343,-2.012527,negative,negative
3068,0e80d061536740a,10,negative,0,0,0,-0.427254,-0.648900,0.311666,-0.438097,...,not_detected,not_detected,-0.184759,0.304858,-0.521453,-0.218957,-0.305787,0.143752,negative,negative
3251,d8a00d4bf3fbc20,11,negative,1,0,0,-0.701917,-0.398276,-1.446987,0.683835,...,not_detected,not_detected,1.355871,-0.290609,-0.394284,-0.081113,-0.552949,-0.215628,negative,negative
3432,788936ca2c9b8a7,4,negative,0,0,0,0.556955,0.478908,-0.140559,-0.213711,...,not_detected,not_detected,-0.815762,-0.588343,-0.376401,0.883794,-1.294433,0.143752,negative,negative
4013,c760816c020185d,9,negative,0,0,0,0.167850,0.290940,0.123239,-0.550290,...,not_detected,not_detected,0.102060,-1.034943,-0.521453,0.229035,-1.047272,-0.215628,negative,negative
4131,5b426e3945f3cf0,11,negative,0,0,0,-0.129702,-0.022340,0.902071,-0.774677,...,not_detected,not_detected,1.060857,-0.513909,0.088559,0.263496,-0.800110,-0.575008,negative,negative
4671,6fe945a69b8383f,3,negative,0,0,0,-0.679027,-0.398276,2.082882,-1.335643,...,not_detected,not_detected,0.020112,-0.886076,-0.511518,-0.942638,-1.541595,0.143752,negative,negative
4978,61dd2fab8e61a9e,12,positive,1,0,0,0.762952,0.478908,-0.555098,0.122869,...,not_detected,not_detected,-0.438800,0.453725,-0.314804,-0.012191,-0.552949,-0.575008,negative,negative
5002,2136a024e2b5c9c,12,positive,1,0,0,-0.381476,-0.335620,-1.245998,-0.774677,...,not_detected,not_detected,-0.955075,0.453725,-0.116103,1.848701,0.435697,1.581271,negative,negative
5004,e5aa8b867b628f4,15,positive,0,1,0,-0.244145,-0.210308,-0.567660,0.683835,...,not_detected,not_detected,-0.717424,-0.737209,-0.330700,-0.046652,-0.552949,-1.653147,negative,negative
5007,9552f94e8cff2bb,0,negative,0,0,0,-0.793470,-0.711556,-0.228491,-0.438097,...,not_detected,not_detected,2.036044,-0.141742,-0.523440,-1.494013,1.424343,-0.215628,negative,negative
5016,c3c08e6b5fb20d7,12,positive,0,0,0,-1.319907,-1.150148,0.273981,-0.325903,...,not_detected,not_detected,1.232949,-0.811643,-0.477739,-1.114943,-0.800110,-1.293767,negative,negative
5027,083b2a959d7b2e8,2,negative,0,1,0,-1.091022,-0.774212,-0.643031,-0.999063,...,not_detected,not_detected,-0.135590,-0.811643,0.114391,-0.977099,0.188535,0.143752,negative,negative
5066,7afa4ae44b27af4,19,negative,0,1,0,-0.267033,-0.398276,-0.730964,0.908221,...,not_detected,not_detected,-0.299487,0.230425,-0.511518,-0.150035,-0.800110,0.143752,negative,negative
5196,d584d2cf7d09e1e,11,positive,0,0,1,-0.450142,0.040316,-0.492289,-0.774677,...,not_detected,not_detected,1.683665,-0.365042,3.086960,-0.356801,-0.552949,-1.293767,negative,negative
5564,32f55e529808065,12,positive,1,0,0,1.152058,0.604220,-0.529975,0.010677,...,not_detected,not_detected,0.667504,-0.290609,0.239572,0.677028,-1.047272,-0.215628,negative,negative
5566,f1c30ed80e63858,14,positive,1,0,0,1.106281,1.042812,-0.253615,-0.438097,...,not_detected,not_detected,0.913350,0.304858,0.227650,1.710857,-1.047272,-0.575008,negative,negative

# COVID19_line_list_data.csv

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [2]:
PATH = os.path.join("data", "COVID19_line_list_data.csv")
data = pd.read_csv(PATH)

In [3]:
data

,id,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,...,recovered,symptom,source,link,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,1,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,"Shenzhen, Guangdong",China,male,66.0,01/03/20,...,0,NaN,Shenzhen Municipal Health Commission,http://wjw.sz.gov.cn/wzx/202001/t20200120_1898...,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,56.0,1/15/2020,...,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,1/21/2020,NaN,First confirmed imported cases in Zhejiang: pa...,Zhejiang,China,male,46.0,01/04/20,...,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,female,60.0,NaN,...,0,NaN,äººæ°æ¥æ¥å®æ¹å¾®å,https://m.weibo.cn/status/4463235401268457?,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,male,58.0,NaN,...,0,NaN,äººæ°æ¥æ¥å®æ¹å¾®å,https://m.weibo.cn/status/4463235401268457?,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,1081,2.0,2/25/2020,NaN,"new COVID-19 patient confirmed in Austria: 24,...",Innsbruck,Austria,NaN,24.0,NaN,...,0,NaN,Jakarta Post,https://www.thejakartapost.com/news/2020/02/25...,NaN,NaN,NaN,NaN,NaN,NaN
1081,1082,1.0,2/24/2020,NaN,new COVID-19 patient confirmed in Afghanistan:...,Afghanistan,Afghanistan,NaN,35.0,NaN,...,0,NaN,Fox News,https://www.foxnews.com/health/afghanistan-fir...,NaN,NaN,NaN,NaN,NaN,NaN
1082,1083,1.0,2/26/2020,NaN,new COVID-19 patient confirmed in Algeria: mal...,Algeria,Algeria,male,NaN,NaN,...,0,NaN,South China Morning Post,https://www.scmp.com/news/china/society/articl...,NaN,NaN,NaN,NaN,NaN,NaN
1083,1084,1.0,2/25/2020,NaN,new COVID-19 patient confirmed in Croatia: mal...,Croatia,Croatia,male,NaN,NaN,...,0,NaN,Reuters,https://www.reuters.com/article/us-croatia-cor...,NaN,NaN,NaN,NaN,NaN,NaN
1084,1085,1.0,2/25/2020,NaN,new COVID-19 patient confirmed in Switzerland:...,Bern,Switzerland,male,70.0,2/17/2020,...,0,NaN,Reuters,https://www.reuters.com/article/uk-switzerland...,NaN,NaN,NaN,NaN,NaN,NaN

# 112000.xlsx

In [17]:
import pandas as pd
import numpy as np
import os

In [18]:
PATH = os.path.join("data", "112000.xlsx")
data = pd.read_excel(PATH)

In [19]:
data["corona_result"] = data["corona_result"].map({"×××××": 1, "×©××××": 0})

In [20]:
data

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-03-22,1.0,0.0,0,0,0,0.0,No,×××¨,Other
1,2020-03-22,1.0,1.0,0,0,0,0.0,No,×××¨,Abroad
2,2020-03-22,0.0,1.0,0,0,0,0.0,Yes,×××¨,Contact with confirmed
3,2020-03-22,1.0,1.0,0,0,0,1.0,Yes,×××¨,Abroad
4,2020-03-22,1.0,0.0,0,0,0,0.0,Yes,× ×§××,Contact with confirmed
...,...,...,...,...,...,...,...,...,...,...
112340,2020-04-11,0.0,0.0,0,0,0,0.0,No,× ×§××,Other
112341,2020-04-11,0.0,0.0,0,0,0,0.0,No,×××¨,Other
112342,2020-04-11,0.0,0.0,0,0,0,0.0,No,× ×§××,Other
112343,2020-04-11,0.0,0.0,0,0,0,0.0,No,× ×§××,Other
112344,2020-04-11,0.0,0.0,0,0,0,0.0,No,× ×§××,Other

In [21]:
data["gender"] = data["gender"].map({"× ×§××": "female", "×××¨": "male"})

In [22]:
data

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-03-22,1.0,0.0,0,0,0,0.0,No,male,Other
1,2020-03-22,1.0,1.0,0,0,0,0.0,No,male,Abroad
2,2020-03-22,0.0,1.0,0,0,0,0.0,Yes,male,Contact with confirmed
3,2020-03-22,1.0,1.0,0,0,0,1.0,Yes,male,Abroad
4,2020-03-22,1.0,0.0,0,0,0,0.0,Yes,female,Contact with confirmed
...,...,...,...,...,...,...,...,...,...,...
112340,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112341,2020-04-11,0.0,0.0,0,0,0,0.0,No,male,Other
112342,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112343,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112344,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other

In [24]:
data.to_csv("train.csv", index = False)

# Reading

In [26]:
df = pd.read_csv("train.csv")

In [27]:
df

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-03-22,1.0,0.0,0,0,0,0.0,No,male,Other
1,2020-03-22,1.0,1.0,0,0,0,0.0,No,male,Abroad
2,2020-03-22,0.0,1.0,0,0,0,0.0,Yes,male,Contact with confirmed
3,2020-03-22,1.0,1.0,0,0,0,1.0,Yes,male,Abroad
4,2020-03-22,1.0,0.0,0,0,0,0.0,Yes,female,Contact with confirmed
...,...,...,...,...,...,...,...,...,...,...
112340,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112341,2020-04-11,0.0,0.0,0,0,0,0.0,No,male,Other
112342,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112343,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other
112344,2020-04-11,0.0,0.0,0,0,0,0.0,No,female,Other